//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_ListItems_Permissions
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int ClassId { get; set; }
        public int SecurityId { get; set; }
        public Nullable<bool> Permission { get; set; }
    
        public virtual Document_DefinitionList_Items Document_DefinitionList_Items { get; set; }
        public virtual Document_Security Document_Security { get; set; }
        public virtual Document_Class Document_Class { get; set; }
    }
}
