//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Permissions
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public Nullable<int> O_Print { get; set; }
        public Nullable<int> O_Save { get; set; }
        public Nullable<int> O_Send { get; set; }
        public Nullable<int> M_Highlight { get; set; }
        public Nullable<int> M_Blackout { get; set; }
        public Nullable<int> M_Note { get; set; }
        public Nullable<bool> CH_Highlight { get; set; }
        public Nullable<bool> CH_Blackout { get; set; }
        public Nullable<bool> CH_Note { get; set; }
        public int SecurityId { get; set; }
        public Nullable<bool> CS_Mail { get; set; }
        public Nullable<bool> DC_Release { get; set; }
    
        public virtual Document_Class Document_Class { get; set; }
        public virtual Document_Security Document_Security { get; set; }
    }
}
