//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Definitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document_Definitions()
        {
            this.Document_DefinitionList_Items = new HashSet<Document_DefinitionList_Items>();
            this.Document_DefinitionPerClass = new HashSet<Document_DefinitionPerClass>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> DataType { get; set; }
        public string Name_PL { get; set; }
        public string Name_RU { get; set; }
        public string Description_RU { get; set; }
        public string Description_PL { get; set; }
        public string Items { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_DefinitionList_Items> Document_DefinitionList_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_DefinitionPerClass> Document_DefinitionPerClass { get; set; }
    }
}
