//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document_Class()
        {
            this.Document_Permissions = new HashSet<Document_Permissions>();
            this.Document_DefinitionPerClass = new HashSet<Document_DefinitionPerClass>();
            this.Document_ListItems_Permissions = new HashSet<Document_ListItems_Permissions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Edit_Date { get; set; }
        public string Edit_User { get; set; }
        public string Name_RU { get; set; }
        public string Description_RU { get; set; }
        public string Table_Name { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Deactivate_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_Permissions> Document_Permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_DefinitionPerClass> Document_DefinitionPerClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_ListItems_Permissions> Document_ListItems_Permissions { get; set; }
    }
}
