//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_DefinitionPerClass
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int DefinitionId { get; set; }
        public string ColumnName { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Deactivate_Date { get; set; }
    
        public virtual Document_Class Document_Class { get; set; }
        public virtual Document_Definitions Document_Definitions { get; set; }
    }
}
