//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_DataTypes_Enum
    {
        public int Id { get; set; }
        public Nullable<int> TypeValue { get; set; }
        public string Name { get; set; }
        public string Name_PL { get; set; }
        public string Name_RU { get; set; }
    }
}
