//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_PermissionsTypes_Enum
    {
        public int Id { get; set; }
        public string AccessObject { get; set; }
        public string AccessType { get; set; }
        public Nullable<int> AccessValue { get; set; }
    }
}
