//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InterfaceLang_PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterfaceLang_PL() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentsManagerRU.InterfaceLang_PL", typeof(InterfaceLang_PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Działanie.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tworzenie.
        /// </summary>
        internal static string actionCreate {
            get {
                return ResourceManager.GetString("actionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuwanie.
        /// </summary>
        internal static string actionDelete {
            get {
                return ResourceManager.GetString("actionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwalnianie.
        /// </summary>
        internal static string actionRelease {
            get {
                return ResourceManager.GetString("actionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisywanie.
        /// </summary>
        internal static string actionSave {
            get {
                return ResourceManager.GetString("actionSave", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utwórz klasę.
        /// </summary>
        internal static string btnAddClass {
            get {
                return ResourceManager.GetString("btnAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj definicję.
        /// </summary>
        internal static string btnAddDefinition {
            get {
                return ResourceManager.GetString("btnAddDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień kolory.
        /// </summary>
        internal static string btnChangeColorLayout {
            get {
                return ResourceManager.GetString("btnChangeColorLayout", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Załącz plik dokumentu.
        /// </summary>
        internal static string btnChooseFile {
            get {
                return ResourceManager.GetString("btnChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamknij.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edycja klas.
        /// </summary>
        internal static string btnContentManager {
            get {
                return ResourceManager.GetString("btnContentManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kontrahenci.
        /// </summary>
        internal static string btnContractors {
            get {
                return ResourceManager.GetString("btnContractors", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Definicje indeksów.
        /// </summary>
        internal static string btnDefinitionManager {
            get {
                return ResourceManager.GetString("btnDefinitionManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń klasę.
        /// </summary>
        internal static string btnDeleteClass {
            get {
                return ResourceManager.GetString("btnDeleteClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń definicję.
        /// </summary>
        internal static string btnDeleteDefinition {
            get {
                return ResourceManager.GetString("btnDeleteDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Możliwość ukrywania obiektów przy podglądzie dokumentu.
        /// </summary>
        internal static string btnlblSecurityAdditionCanHide {
            get {
                return ResourceManager.GetString("btnlblSecurityAdditionCanHide", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pełen dostęp do tworzenia, edycji i usuwania obiektów.
        /// </summary>
        internal static string btnlblSecurityAdditionFull {
            get {
                return ResourceManager.GetString("btnlblSecurityAdditionFull", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostępna możliwość tworzenia nowych obiektów.
        /// </summary>
        internal static string btnlblSecurityAdditionNew {
            get {
                return ResourceManager.GetString("btnlblSecurityAdditionNew", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak dostępu do tworzenia i edycji obiektów.
        /// </summary>
        internal static string btnlblSecurityAdditionNothing {
            get {
                return ResourceManager.GetString("btnlblSecurityAdditionNothing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuwanie.
        /// </summary>
        internal static string btnlblSecurityClassDelete {
            get {
                return ResourceManager.GetString("btnlblSecurityClassDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwalnianie.
        /// </summary>
        internal static string btnlblSecurityClassEdit {
            get {
                return ResourceManager.GetString("btnlblSecurityClassEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pełny dostęp.
        /// </summary>
        internal static string btnlblSecurityClassFull {
            get {
                return ResourceManager.GetString("btnlblSecurityClassFull", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak dostępu.
        /// </summary>
        internal static string btnlblSecurityClassNothing {
            get {
                return ResourceManager.GetString("btnlblSecurityClassNothing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odczytywanie.
        /// </summary>
        internal static string btnlblSecurityClassRead {
            get {
                return ResourceManager.GetString("btnlblSecurityClassRead", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operacja dostępna, z możliwością ukrycia pól specjalnych.
        /// </summary>
        internal static string btnlblSecurityOperationFull {
            get {
                return ResourceManager.GetString("btnlblSecurityOperationFull", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak dostępu do wykonania operacji.
        /// </summary>
        internal static string btnlblSecurityOperationNone {
            get {
                return ResourceManager.GetString("btnlblSecurityOperationNone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operacja dostępna, bez możliwości ukrycia pól specjalnych.
        /// </summary>
        internal static string btnlblSecurityOperationOnlyWith {
            get {
                return ResourceManager.GetString("btnlblSecurityOperationOnlyWith", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Poświadczenie zezwalania użytkownikowi na zwalnianie dokumentów.
        /// </summary>
        internal static string btnPermissionCanRelease {
            get {
                return ResourceManager.GetString("btnPermissionCanRelease", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wysyłaj email do użytkownika lub grupy na zwolnienie dokumentu w danej klasie.
        /// </summary>
        internal static string btnPermissionEmailOnRelease {
            get {
                return ResourceManager.GetString("btnPermissionEmailOnRelease", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do klas.
        /// </summary>
        internal static string btnPermissionsClass {
            get {
                return ResourceManager.GetString("btnPermissionsClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp przez listy.
        /// </summary>
        internal static string btnPermissionsRecords {
            get {
                return ResourceManager.GetString("btnPermissionsRecords", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odśwież.
        /// </summary>
        internal static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwolnij dokument.
        /// </summary>
        internal static string btnReleaseDocument {
            get {
                return ResourceManager.GetString("btnReleaseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwolnij dokument.
        /// </summary>
        internal static string btnReleaseDocument1 {
            get {
                return ResourceManager.GetString("btnReleaseDocument1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz klasę.
        /// </summary>
        internal static string btnSaveClass {
            get {
                return ResourceManager.GetString("btnSaveClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz definicję.
        /// </summary>
        internal static string btnSaveDefinition {
            get {
                return ResourceManager.GetString("btnSaveDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szukaj.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownicy.
        /// </summary>
        internal static string btnUsers {
            get {
                return ResourceManager.GetString("btnUsers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis.
        /// </summary>
        internal static string descriptionDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("descriptionDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pełny dostęp.
        /// </summary>
        internal static string dgvCBColumnFull {
            get {
                return ResourceManager.GetString("dgvCBColumnFull", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odczyt.
        /// </summary>
        internal static string dgvCBColumnRead {
            get {
                return ResourceManager.GetString("dgvCBColumnRead", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edycja.
        /// </summary>
        internal static string dgvCBColumnRelease {
            get {
                return ResourceManager.GetString("dgvCBColumnRelease", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktywny.
        /// </summary>
        internal static string dgvColumnActive {
            get {
                return ResourceManager.GetString("dgvColumnActive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klasa.
        /// </summary>
        internal static string dgvColumnClassName {
            get {
                return ResourceManager.GetString("dgvColumnClassName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kontrahent.
        /// </summary>
        internal static string dgvColumnContractor {
            get {
                return ResourceManager.GetString("dgvColumnContractor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis.
        /// </summary>
        internal static string dgvColumnDescription {
            get {
                return ResourceManager.GetString("dgvColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jest.
        /// </summary>
        internal static string dgvColumnGroupAdded {
            get {
                return ResourceManager.GetString("dgvColumnGroupAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis.
        /// </summary>
        internal static string dgvColumnGroupDecription {
            get {
                return ResourceManager.GetString("dgvColumnGroupDecription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        internal static string dgvColumnGroupName {
            get {
                return ResourceManager.GetString("dgvColumnGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lp..
        /// </summary>
        internal static string dgvColumnGroupNumber {
            get {
                return ResourceManager.GetString("dgvColumnGroupNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa rekordu.
        /// </summary>
        internal static string dgvColumnItemName {
            get {
                return ResourceManager.GetString("dgvColumnItemName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login.
        /// </summary>
        internal static string dgvColumnLogin {
            get {
                return ResourceManager.GetString("dgvColumnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        internal static string dgvColumnName {
            get {
                return ResourceManager.GetString("dgvColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data wpływu.
        /// </summary>
        internal static string dgvColumnReceiptDate {
            get {
                return ResourceManager.GetString("dgvColumnReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data zwolnienia.
        /// </summary>
        internal static string dgvColumnReleaseDate {
            get {
                return ResourceManager.GetString("dgvColumnReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Administrator.
        /// </summary>
        internal static string dgvColumnSecurity {
            get {
                return ResourceManager.GetString("dgvColumnSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktyw..
        /// </summary>
        internal static string dgvColumnSecurityActive {
            get {
                return ResourceManager.GetString("dgvColumnSecurityActive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Admin.
        /// </summary>
        internal static string dgvColumnSecurityAdmin {
            get {
                return ResourceManager.GetString("dgvColumnSecurityAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis.
        /// </summary>
        internal static string dgvColumnSecurityDescription {
            get {
                return ResourceManager.GetString("dgvColumnSecurityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        internal static string dgvColumnSecurityName {
            get {
                return ResourceManager.GetString("dgvColumnSecurityName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typ.
        /// </summary>
        internal static string dgvColumnSecurityType {
            get {
                return ResourceManager.GetString("dgvColumnSecurityType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jest.
        /// </summary>
        internal static string dgvColumnUserAdded {
            get {
                return ResourceManager.GetString("dgvColumnUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        internal static string dgvColumnUserName {
            get {
                return ResourceManager.GetString("dgvColumnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lp..
        /// </summary>
        internal static string dgvColumnUserNumber {
            get {
                return ResourceManager.GetString("dgvColumnUserNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utwórz klasę.
        /// </summary>
        internal static string frmAddClass {
            get {
                return ResourceManager.GetString("frmAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwolnij dokument.
        /// </summary>
        internal static string frmAddDocument {
            get {
                return ResourceManager.GetString("frmAddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edycja klas.
        /// </summary>
        internal static string frmContentManager {
            get {
                return ResourceManager.GetString("frmContentManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edycja definicji indeksów.
        /// </summary>
        internal static string frmDefinitionManager {
            get {
                return ResourceManager.GetString("frmDefinitionManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szczegóły.
        /// </summary>
        internal static string frmDetails {
            get {
                return ResourceManager.GetString("frmDetails", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edycja dokumentu.
        /// </summary>
        internal static string frmEditDocument {
            get {
                return ResourceManager.GetString("frmEditDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podmiana pliku dokumentu.
        /// </summary>
        internal static string frmEditDocumentFile {
            get {
                return ResourceManager.GetString("frmEditDocumentFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Menedżer rekordów list zaawansowanych.
        /// </summary>
        internal static string frmListManager {
            get {
                return ResourceManager.GetString("frmListManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Narzędzia migracji.
        /// </summary>
        internal static string frmMigrationTools {
            get {
                return ResourceManager.GetString("frmMigrationTools", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzanie dostępem do klas przez rekordy list.
        /// </summary>
        internal static string frmPermissionListItemsManager {
            get {
                return ResourceManager.GetString("frmPermissionListItemsManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do klas.
        /// </summary>
        internal static string frmPermissionManager {
            get {
                return ResourceManager.GetString("frmPermissionManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownicy i grupy.
        /// </summary>
        internal static string frmSecurityManager {
            get {
                return ResourceManager.GetString("frmSecurityManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        /// </summary>
        internal static string frmSettings {
            get {
                return ResourceManager.GetString("frmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownicy.
        /// </summary>
        internal static string frmUsersManager {
            get {
                return ResourceManager.GetString("frmUsersManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parametry klasy.
        /// </summary>
        internal static string gbClass {
            get {
                return ResourceManager.GetString("gbClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Informacje o klasie.
        /// </summary>
        internal static string gbClassInfo {
            get {
                return ResourceManager.GetString("gbClassInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Informacje o definicji indeksu.
        /// </summary>
        internal static string gbDefinitionInfo {
            get {
                return ResourceManager.GetString("gbDefinitionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parametry dokumentu.
        /// </summary>
        internal static string gbDocument {
            get {
                return ResourceManager.GetString("gbDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Informacje o dokumencie.
        /// </summary>
        internal static string gbDocumentInfo {
            get {
                return ResourceManager.GetString("gbDocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik.
        /// </summary>
        internal static string gbFile {
            get {
                return ResourceManager.GetString("gbFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Indeksy.
        /// </summary>
        internal static string gbIndexes {
            get {
                return ResourceManager.GetString("gbIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zawartość listy.
        /// </summary>
        internal static string gbListItems {
            get {
                return ResourceManager.GetString("gbListItems", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podgląd.
        /// </summary>
        internal static string gbPreview {
            get {
                return ResourceManager.GetString("gbPreview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dokument nadrzędny.
        /// </summary>
        internal static string gbPrimaryObject {
            get {
                return ResourceManager.GetString("gbPrimaryObject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dokumenty podrzędne.
        /// </summary>
        internal static string gbSecondaryObjects {
            get {
                return ResourceManager.GetString("gbSecondaryObjects", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia aplikacji.
        /// </summary>
        internal static string gbSettings {
            get {
                return ResourceManager.GetString("gbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Angielski.
        /// </summary>
        internal static string langEN {
            get {
                return ResourceManager.GetString("langEN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polski.
        /// </summary>
        internal static string langPL {
            get {
                return ResourceManager.GetString("langPL", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rosyjski.
        /// </summary>
        internal static string langRU {
            get {
                return ResourceManager.GetString("langRU", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktywna:.
        /// </summary>
        internal static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktywny:.
        /// </summary>
        internal static string lblActive2 {
            get {
                return ResourceManager.GetString("lblActive2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktywna:.
        /// </summary>
        internal static string lblActive3 {
            get {
                return ResourceManager.GetString("lblActive3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powiązana klasa:.
        /// </summary>
        internal static string lblAssignClass {
            get {
                return ResourceManager.GetString("lblAssignClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powiązany dokument:.
        /// </summary>
        internal static string lblAssignDocument {
            get {
                return ResourceManager.GetString("lblAssignDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klasa:.
        /// </summary>
        internal static string lblClass {
            get {
                return ResourceManager.GetString("lblClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klasa:.
        /// </summary>
        internal static string lblClass2 {
            get {
                return ResourceManager.GetString("lblClass2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klasa dokumentu.
        /// </summary>
        internal static string lblClassTitle {
            get {
                return ResourceManager.GetString("lblClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typ indeksu:.
        /// </summary>
        internal static string lblDataType {
            get {
                return ResourceManager.GetString("lblDataType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data deaktywacji:.
        /// </summary>
        internal static string lblDeactivateDate {
            get {
                return ResourceManager.GetString("lblDeactivateDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Definicja:.
        /// </summary>
        internal static string lblDefinition {
            get {
                return ResourceManager.GetString("lblDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wartość domyślna:.
        /// </summary>
        internal static string lblDefinitionDefault {
            get {
                return ResourceManager.GetString("lblDefinitionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rekordy listy prostej (Jedna linijka - jeden rekord):.
        /// </summary>
        internal static string lblDefinitionList {
            get {
                return ResourceManager.GetString("lblDefinitionList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rekordy listy zaawansowanej:.
        /// </summary>
        internal static string lblDefinitionListAdv {
            get {
                return ResourceManager.GetString("lblDefinitionListAdv", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zakres użycia indeksu:.
        /// </summary>
        internal static string lblDefinitionRange {
            get {
                return ResourceManager.GetString("lblDefinitionRange", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń dokument.
        /// </summary>
        internal static string lblDeleteDocument {
            get {
                return ResourceManager.GetString("lblDeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuwaj plik po zwolnieniu:.
        /// </summary>
        internal static string lblDeleting {
            get {
                return ResourceManager.GetString("lblDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis:.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis:.
        /// </summary>
        internal static string lblDescription2 {
            get {
                return ResourceManager.GetString("lblDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis:.
        /// </summary>
        internal static string lblDescriptionPL1 {
            get {
                return ResourceManager.GetString("lblDescriptionPL1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis RU:.
        /// </summary>
        internal static string lblDescriptionRU {
            get {
                return ResourceManager.GetString("lblDescriptionRU", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis RU:.
        /// </summary>
        internal static string lblDescriptionRU1 {
            get {
                return ResourceManager.GetString("lblDescriptionRU1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dokument:.
        /// </summary>
        internal static string lblDocument {
            get {
                return ResourceManager.GetString("lblDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klasy.
        /// </summary>
        internal static string lblDocumentClass {
            get {
                return ResourceManager.GetString("lblDocumentClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Definicje indeksów.
        /// </summary>
        internal static string lblDocumentDefinition {
            get {
                return ResourceManager.GetString("lblDocumentDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rekordy listy.
        /// </summary>
        internal static string lblDocumentListItems {
            get {
                return ResourceManager.GetString("lblDocumentListItems", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj.
        /// </summary>
        internal static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyślij emaila po zwolnieniu dokumentu:.
        /// </summary>
        internal static string lblEmailOnRelease {
            get {
                return ResourceManager.GetString("lblEmailOnRelease", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Definicje indeksów:.
        /// </summary>
        internal static string lblExistingDefinitions {
            get {
                return ResourceManager.GetString("lblExistingDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik:.
        /// </summary>
        internal static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wielkość pliku:.
        /// </summary>
        internal static string lblFileSize {
            get {
                return ResourceManager.GetString("lblFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grupy użytkowników.
        /// </summary>
        internal static string lblGroups {
            get {
                return ResourceManager.GetString("lblGroups", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grupy Active Directory.
        /// </summary>
        internal static string lblGroupTitle {
            get {
                return ResourceManager.GetString("lblGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wymagane:.
        /// </summary>
        internal static string lblIsRequired {
            get {
                return ResourceManager.GetString("lblIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Liczba rekordów listy:.
        /// </summary>
        internal static string lblListRecordCount {
            get {
                return ResourceManager.GetString("lblListRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login.
        /// </summary>
        internal static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa:.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa:.
        /// </summary>
        internal static string lblName2 {
            get {
                return ResourceManager.GetString("lblName2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa:.
        /// </summary>
        internal static string lblNamePL1 {
            get {
                return ResourceManager.GetString("lblNamePL1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa RU:.
        /// </summary>
        internal static string lblNameRU {
            get {
                return ResourceManager.GetString("lblNameRU", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa RU:.
        /// </summary>
        internal static string lblNameRU1 {
            get {
                return ResourceManager.GetString("lblNameRU1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowy adres folderu serwera:.
        /// </summary>
        internal static string lblNewServerPath {
            get {
                return ResourceManager.GetString("lblNewServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Oryginalna nazwa:.
        /// </summary>
        internal static string lblOriginalName {
            get {
                return ResourceManager.GetString("lblOriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwalnianie.
        /// </summary>
        internal static string lblPermissionsNotificationsTitle {
            get {
                return ResourceManager.GetString("lblPermissionsNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data wpływu:.
        /// </summary>
        internal static string lblReceiptDate {
            get {
                return ResourceManager.GetString("lblReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwolniony przez:.
        /// </summary>
        internal static string lblRelasedBy {
            get {
                return ResourceManager.GetString("lblRelasedBy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data zwolnienia:.
        /// </summary>
        internal static string lblReleaseDate {
            get {
                return ResourceManager.GetString("lblReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu * Wymagane.
        /// </summary>
        internal static string lblRequired {
            get {
                return ResourceManager.GetString("lblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz klasę.
        /// </summary>
        internal static string lblSaveClass {
            get {
                return ResourceManager.GetString("lblSaveClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz dokument.
        /// </summary>
        internal static string lblSaveDocument {
            get {
                return ResourceManager.GetString("lblSaveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyszukiwanie.
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa dokumentu:.
        /// </summary>
        internal static string lblSearchDocName {
            get {
                return ResourceManager.GetString("lblSearchDocName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data zwolnienia (Od - Do):.
        /// </summary>
        internal static string lblSearchReleaseDate {
            get {
                return ResourceManager.GetString("lblSearchReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do zaciemnień.
        /// </summary>
        internal static string lblSecurityAdditionBlackoutTitle {
            get {
                return ResourceManager.GetString("lblSecurityAdditionBlackoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do podświetleń.
        /// </summary>
        internal static string lblSecurityAdditionHighligtTitle {
            get {
                return ResourceManager.GetString("lblSecurityAdditionHighligtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do notatek.
        /// </summary>
        internal static string lblSecurityAdditionNoteTitle {
            get {
                return ResourceManager.GetString("lblSecurityAdditionNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do klas.
        /// </summary>
        internal static string lblSecurityClassSectionTitle {
            get {
                return ResourceManager.GetString("lblSecurityClassSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do wydruku.
        /// </summary>
        internal static string lblSecurityPrintSectionTitle {
            get {
                return ResourceManager.GetString("lblSecurityPrintSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do  zapisu.
        /// </summary>
        internal static string lblSecuritySaveSectionTitle {
            get {
                return ResourceManager.GetString("lblSecuritySaveSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do wysyłki.
        /// </summary>
        internal static string lblSecuritySendSectionTitle {
            get {
                return ResourceManager.GetString("lblSecuritySendSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaimportowane grupy i użytkownicy.
        /// </summary>
        internal static string lblSecurityTitle {
            get {
                return ResourceManager.GetString("lblSecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres folderu serwera:.
        /// </summary>
        internal static string lblServerPath {
            get {
                return ResourceManager.GetString("lblServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (liczba).
        /// </summary>
        internal static string lblTypeNumber {
            get {
                return ResourceManager.GetString("lblTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu URL:.
        /// </summary>
        internal static string lblURL {
            get {
                return ResourceManager.GetString("lblURL", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Używaj zewnętrznej aplikacji do otwierania dokumentów:.
        /// </summary>
        internal static string lblUseExternalViewer {
            get {
                return ResourceManager.GetString("lblUseExternalViewer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownicy Active Directory.
        /// </summary>
        internal static string lblUserTitle {
            get {
                return ResourceManager.GetString("lblUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz nadać nazwę dla dokumentu!.
        /// </summary>
        internal static string msg01 {
            get {
                return ResourceManager.GetString("msg01", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz wybrać plik, który ma zostać zwolniony!.
        /// </summary>
        internal static string msg02 {
            get {
                return ResourceManager.GetString("msg02", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwalnianie dokumentu zakończone sukcesem..
        /// </summary>
        internal static string msg03 {
            get {
                return ResourceManager.GetString("msg03", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił problem w trakcie zwalniania dokumentu!.
        /// </summary>
        internal static string msg04 {
            get {
                return ResourceManager.GetString("msg04", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz podać nazwę dla nowej klasy!.
        /// </summary>
        internal static string msg05 {
            get {
                return ResourceManager.GetString("msg05", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podana nazwa dla klasy dokumentów już jest w użyciu!.
        /// </summary>
        internal static string msg06 {
            get {
                return ResourceManager.GetString("msg06", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klasa została poprawnie utworzona..
        /// </summary>
        internal static string msg07 {
            get {
                return ResourceManager.GetString("msg07", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił problem w trakcie tworzenia nowej klasy!.
        /// </summary>
        internal static string msg08 {
            get {
                return ResourceManager.GetString("msg08", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz podać wartość domyślną!.
        /// </summary>
        internal static string msg09 {
            get {
                return ResourceManager.GetString("msg09", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz podać nazwę dla klasy w języku rosyjskim!.
        /// </summary>
        internal static string msg10 {
            get {
                return ResourceManager.GetString("msg10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podana nazwa dla klasy dokumentów w języku rosyjskim już jest w użyciu!.
        /// </summary>
        internal static string msg11 {
            get {
                return ResourceManager.GetString("msg11", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu W systemie otwarta jest już aplikacja..
        /// </summary>
        internal static string msg12 {
            get {
                return ResourceManager.GetString("msg12", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownik nie ma praw do uruchomienia aplikacji!.
        /// </summary>
        internal static string msg13 {
            get {
                return ResourceManager.GetString("msg13", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skontaktuj się z administratorem..
        /// </summary>
        internal static string msg14 {
            get {
                return ResourceManager.GetString("msg14", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd uruchamiania aplikacji.
        /// </summary>
        internal static string msg15 {
            get {
                return ResourceManager.GetString("msg15", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa dokumentu musi być unikalna w obrębie klasy!.
        /// </summary>
        internal static string msg16 {
            get {
                return ResourceManager.GetString("msg16", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podany tekst ma niepoprawny format!.
        /// </summary>
        internal static string msg17 {
            get {
                return ResourceManager.GetString("msg17", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jedno z pól na formularzu zostało zmodyfikowane, ale nie zapisane. Zamknąć bez zapisywania?.
        /// </summary>
        internal static string msg18 {
            get {
                return ResourceManager.GetString("msg18", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uwaga!.
        /// </summary>
        internal static string msg19 {
            get {
                return ResourceManager.GetString("msg19", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zbyt długi adres pliku! Wybierz plik ponownie..
        /// </summary>
        internal static string msg20 {
            get {
                return ResourceManager.GetString("msg20", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz usunąć rekord listy?.
        /// </summary>
        internal static string msg21 {
            get {
                return ResourceManager.GetString("msg21", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz wybrać typ indeksu!.
        /// </summary>
        internal static string msg22 {
            get {
                return ResourceManager.GetString("msg22", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz trwale usunąć następujący dokument:.
        /// </summary>
        internal static string msg23 {
            get {
                return ResourceManager.GetString("msg23", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz podać nazwę unikalną w obrębie klasy i języka!.
        /// </summary>
        internal static string msg24 {
            get {
                return ResourceManager.GetString("msg24", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dokument nie został usunięty!.
        /// </summary>
        internal static string msg25 {
            get {
                return ResourceManager.GetString("msg25", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz podać wartość!.
        /// </summary>
        internal static string msg26 {
            get {
                return ResourceManager.GetString("msg26", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz podać nazwę dla nowego indeksu w języku polskim!.
        /// </summary>
        internal static string msg27 {
            get {
                return ResourceManager.GetString("msg27", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz podać nazwę dla nowego indeksu w języku rosyjskim!.
        /// </summary>
        internal static string msg28 {
            get {
                return ResourceManager.GetString("msg28", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista wpisów zawiera za dużo znaków!.
        /// </summary>
        internal static string msg29 {
            get {
                return ResourceManager.GetString("msg29", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potwierdź zmianę statusu aktywności dokumentu.
        /// </summary>
        internal static string msg30 {
            get {
                return ResourceManager.GetString("msg30", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz wybrać definicję indeksu!.
        /// </summary>
        internal static string msg31 {
            get {
                return ResourceManager.GetString("msg31", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz dokument i klasę do powiązania, lub wyczyść powiązania!.
        /// </summary>
        internal static string msg32 {
            get {
                return ResourceManager.GetString("msg32", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz podać unikalną nazwę!.
        /// </summary>
        internal static string msg33 {
            get {
                return ResourceManager.GetString("msg33", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz wybrać wartość z listy!.
        /// </summary>
        internal static string msg34 {
            get {
                return ResourceManager.GetString("msg34", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Liczba wystąpień w bazie danych:.
        /// </summary>
        internal static string msg35 {
            get {
                return ResourceManager.GetString("msg35", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił problem z dostępem do serwera danych! Powiadom IT..
        /// </summary>
        internal static string msgAccessError {
            get {
                return ResourceManager.GetString("msgAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz zastosować zmianę dla wszystkich użytkowników na liście?.
        /// </summary>
        internal static string msgApplyToAllQuestion {
            get {
                return ResourceManager.GetString("msgApplyToAllQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj.
        /// </summary>
        internal static string msgCancel {
            get {
                return ResourceManager.GetString("msgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj edycję.
        /// </summary>
        internal static string msgCancelEdit {
            get {
                return ResourceManager.GetString("msgCancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potwierdź usunięcie.
        /// </summary>
        internal static string msgDelete {
            get {
                return ResourceManager.GetString("msgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił problem w trakcie trwania operacji!.
        /// </summary>
        internal static string msgFailed {
            get {
                return ResourceManager.GetString("msgFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie.
        /// </summary>
        internal static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak pliku do wyświetlenia!.
        /// </summary>
        internal static string msgNoFile {
            get {
                return ResourceManager.GetString("msgNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak dostępu do dokumentu!.
        /// </summary>
        internal static string msgNoPermissionToDocument {
            get {
                return ResourceManager.GetString("msgNoPermissionToDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operacja zakończona sukcesem!.
        /// </summary>
        internal static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika nie może być pusta!.
        /// </summary>
        internal static string msgVal01 {
            get {
                return ResourceManager.GetString("msgVal01", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz podać unikalną nazwę użytkownika!.
        /// </summary>
        internal static string msgVal02 {
            get {
                return ResourceManager.GetString("msgVal02", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tak.
        /// </summary>
        internal static string msgYes {
            get {
                return ResourceManager.GetString("msgYes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        internal static string nameDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("nameDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obiekt powiązania indeksu z klasą .
        /// </summary>
        internal static string objectAssociatedDefinition {
            get {
                return ResourceManager.GetString("objectAssociatedDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klasa.
        /// </summary>
        internal static string objectClass {
            get {
                return ResourceManager.GetString("objectClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Definicja indeksu.
        /// </summary>
        internal static string objectDefinition {
            get {
                return ResourceManager.GetString("objectDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dokument.
        /// </summary>
        internal static string objectDocument {
            get {
                return ResourceManager.GetString("objectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stara nazwa.
        /// </summary>
        internal static string oldFileNameDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("oldFileNameDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rekordy listy.
        /// </summary>
        internal static string pcAdvancedList {
            get {
                return ResourceManager.GetString("pcAdvancedList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szczegóły definicji.
        /// </summary>
        internal static string pcDefinition {
            get {
                return ResourceManager.GetString("pcDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rekordy listy.
        /// </summary>
        internal static string pcSimpleList {
            get {
                return ResourceManager.GetString("pcSimpleList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wszystkie klasy.
        /// </summary>
        internal static string rbDefinitionRangeAll {
            get {
                return ResourceManager.GetString("rbDefinitionRangeAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiele klas.
        /// </summary>
        internal static string rbDefinitionRangeMany {
            get {
                return ResourceManager.GetString("rbDefinitionRangeMany", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jedna klasa.
        /// </summary>
        internal static string rbDefinitionRangeSingle {
            get {
                return ResourceManager.GetString("rbDefinitionRangeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klasy i Powiadomienia.
        /// </summary>
        internal static string rbPermissionClass {
            get {
                return ResourceManager.GetString("rbPermissionClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Notatki, podświetlenia, zaciemnienia.
        /// </summary>
        internal static string rbSecurityAdds {
            get {
                return ResourceManager.GetString("rbSecurityAdds", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operacje na dokumentach.
        /// </summary>
        internal static string rbSecurityClass {
            get {
                return ResourceManager.GetString("rbSecurityClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data zwolnienia.
        /// </summary>
        internal static string releaseDateDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("releaseDateDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grupa.
        /// </summary>
        internal static string securityTypeGroup {
            get {
                return ResourceManager.GetString("securityTypeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownik.
        /// </summary>
        internal static string securityTypeUser {
            get {
                return ResourceManager.GetString("securityTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NIE (Zaznaczono).
        /// </summary>
        internal static string strNoActive {
            get {
                return ResourceManager.GetString("strNoActive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NIE.
        /// </summary>
        internal static string strNoInactive {
            get {
                return ResourceManager.GetString("strNoInactive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu TAK (zaznaczono).
        /// </summary>
        internal static string strYesActive {
            get {
                return ResourceManager.GetString("strYesActive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu TAK.
        /// </summary>
        internal static string strYesInactive {
            get {
                return ResourceManager.GetString("strYesInactive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wersja aplikacji: .
        /// </summary>
        internal static string titleAppVersion {
            get {
                return ResourceManager.GetString("titleAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Informacje o powiązanych dokumentach.
        /// </summary>
        internal static string tpAssignedDetails {
            get {
                return ResourceManager.GetString("tpAssignedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podstawowe informacje.
        /// </summary>
        internal static string tpSimpleDetails {
            get {
                return ResourceManager.GetString("tpSimpleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Akcja.
        /// </summary>
        internal static string tsddbAction {
            get {
                return ResourceManager.GetString("tsddbAction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Administracja.
        /// </summary>
        internal static string tsddbAdmin {
            get {
                return ResourceManager.GetString("tsddbAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Język.
        /// </summary>
        internal static string tsddLanguage {
            get {
                return ResourceManager.GetString("tsddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamknij.
        /// </summary>
        internal static string tsmiClose {
            get {
                return ResourceManager.GetString("tsmiClose", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edycja klas.
        /// </summary>
        internal static string tsmiContentManager {
            get {
                return ResourceManager.GetString("tsmiContentManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edycja definicji indeksów.
        /// </summary>
        internal static string tsmiDefinitionManager {
            get {
                return ResourceManager.GetString("tsmiDefinitionManager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utwórz klasę.
        /// </summary>
        internal static string tsmiNewClass {
            get {
                return ResourceManager.GetString("tsmiNewClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp do klas.
        /// </summary>
        internal static string tsmiPermissions {
            get {
                return ResourceManager.GetString("tsmiPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp przez listy.
        /// </summary>
        internal static string tsmiPermissionsRecords {
            get {
                return ResourceManager.GetString("tsmiPermissionsRecords", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odśwież.
        /// </summary>
        internal static string tsmiRefresh {
            get {
                return ResourceManager.GetString("tsmiRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zwolnij dokument.
        /// </summary>
        internal static string tsmiReleaseDocument {
            get {
                return ResourceManager.GetString("tsmiReleaseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        /// </summary>
        internal static string tsmiSettings {
            get {
                return ResourceManager.GetString("tsmiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownicy.
        /// </summary>
        internal static string tsmiUsers {
            get {
                return ResourceManager.GetString("tsmiUsers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pokaż szczegóły.
        /// </summary>
        internal static string ttDetails {
            get {
                return ResourceManager.GetString("ttDetails", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz dokument.
        /// </summary>
        internal static string ttOpen {
            get {
                return ResourceManager.GetString("ttOpen", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz folder.
        /// </summary>
        internal static string ttOpenDirectory {
            get {
                return ResourceManager.GetString("ttOpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz ścieżkę folderu.
        /// </summary>
        internal static string ttSavePath {
            get {
                return ResourceManager.GetString("ttSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu URL.
        /// </summary>
        internal static string uRLDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("uRLDataGridViewTextBoxColumn", resourceCulture);
            }
        }
    }
}
