//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InterfaceLang_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterfaceLang_EN() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentsManagerRU.InterfaceLang_EN", typeof(InterfaceLang_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Class.
        /// </summary>
        internal static string btnAddClass {
            get {
                return ResourceManager.GetString("btnAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose document.
        /// </summary>
        internal static string btnChooseFile {
            get {
                return ResourceManager.GetString("btnChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Refresh.
        /// </summary>
        internal static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Release document.
        /// </summary>
        internal static string btnReleaseDocument {
            get {
                return ResourceManager.GetString("btnReleaseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description.
        /// </summary>
        internal static string descriptionDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("descriptionDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add class.
        /// </summary>
        internal static string frmAddClass {
            get {
                return ResourceManager.GetString("frmAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Release document.
        /// </summary>
        internal static string frmAddDocument {
            get {
                return ResourceManager.GetString("frmAddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manager of administrative documents.
        /// </summary>
        internal static string frmMain {
            get {
                return ResourceManager.GetString("frmMain", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Class parameters.
        /// </summary>
        internal static string gbClass {
            get {
                return ResourceManager.GetString("gbClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Class information.
        /// </summary>
        internal static string gbClassInfo {
            get {
                return ResourceManager.GetString("gbClassInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Documents parameters.
        /// </summary>
        internal static string gbDocument {
            get {
                return ResourceManager.GetString("gbDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Documents information.
        /// </summary>
        internal static string gbDocumentInfo {
            get {
                return ResourceManager.GetString("gbDocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Class:.
        /// </summary>
        internal static string lblClass {
            get {
                return ResourceManager.GetString("lblClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Document of class.
        /// </summary>
        internal static string lblClassTitle {
            get {
                return ResourceManager.GetString("lblClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description:.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description:.
        /// </summary>
        internal static string lblDescription2 {
            get {
                return ResourceManager.GetString("lblDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File:.
        /// </summary>
        internal static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name:.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name:.
        /// </summary>
        internal static string lblName2 {
            get {
                return ResourceManager.GetString("lblName2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Original name:.
        /// </summary>
        internal static string lblOriginalName {
            get {
                return ResourceManager.GetString("lblOriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Release by:.
        /// </summary>
        internal static string lblRelasedBy {
            get {
                return ResourceManager.GetString("lblRelasedBy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Release date:.
        /// </summary>
        internal static string lblReleaseDate {
            get {
                return ResourceManager.GetString("lblReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu URL:.
        /// </summary>
        internal static string lblURL {
            get {
                return ResourceManager.GetString("lblURL", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter name for document!.
        /// </summary>
        internal static string msg1 {
            get {
                return ResourceManager.GetString("msg1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose file to release!.
        /// </summary>
        internal static string msg2 {
            get {
                return ResourceManager.GetString("msg2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Releasing the document successful..
        /// </summary>
        internal static string msg3 {
            get {
                return ResourceManager.GetString("msg3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There was a problem during the release of the document!.
        /// </summary>
        internal static string msg4 {
            get {
                return ResourceManager.GetString("msg4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter name for new class!.
        /// </summary>
        internal static string msg5 {
            get {
                return ResourceManager.GetString("msg5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Entered name for new class already exist!.
        /// </summary>
        internal static string msg6 {
            get {
                return ResourceManager.GetString("msg6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Creating class succesful.
        /// </summary>
        internal static string msg7 {
            get {
                return ResourceManager.GetString("msg7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There was a problem during the creating of the new class!.
        /// </summary>
        internal static string msg8 {
            get {
                return ResourceManager.GetString("msg8", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        internal static string nameDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("nameDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Old name.
        /// </summary>
        internal static string oldFileNameDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("oldFileNameDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Release date.
        /// </summary>
        internal static string releaseDateDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("releaseDateDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu App version:.
        /// </summary>
        internal static string titleAppVersion {
            get {
                return ResourceManager.GetString("titleAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action.
        /// </summary>
        internal static string tsddbAction {
            get {
                return ResourceManager.GetString("tsddbAction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        internal static string tsddbFile {
            get {
                return ResourceManager.GetString("tsddbFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language.
        /// </summary>
        internal static string tsddLanguage {
            get {
                return ResourceManager.GetString("tsddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close.
        /// </summary>
        internal static string tsmiClose {
            get {
                return ResourceManager.GetString("tsmiClose", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New class.
        /// </summary>
        internal static string tsmiNewClass {
            get {
                return ResourceManager.GetString("tsmiNewClass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Refresh.
        /// </summary>
        internal static string tsmiRefresh {
            get {
                return ResourceManager.GetString("tsmiRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Release document.
        /// </summary>
        internal static string tsmiReleaseDocument {
            get {
                return ResourceManager.GetString("tsmiReleaseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu URL.
        /// </summary>
        internal static string uRLDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("uRLDataGridViewTextBoxColumn", resourceCulture);
            }
        }
    }
}
