//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsManagerRU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oznaczenia
    {
        public int Id { get; set; }
        public int Class_Id { get; set; }
        public long Document_Id { get; set; }
        public int Typ { get; set; }
        public int Strona { get; set; }
        public int Pozycja { get; set; }
        public double Left { get; set; }
        public double Top { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public string Text { get; set; }
    }
}
